engines/candidate/config/routes.rb
Candidate::Engine.routes.draw do
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]

  resources :cadastres
  resources :notifications

  namespace :attendance do 
    resources :tickets do 
      resources :steps, controller: :ticket_steps do 
        resources :cadastres
      end
    end
  end
end

engines/candidate/app/models/candidate/application_record.rb
module Candidate
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/candidate/app/models/candidate/attendance/step.rb
require_dependency 'support/attendance/step'

module Attendance
  class Step < Support::Attendance::Step
    
  end
end

engines/candidate/app/models/candidate/attendance/step_document.rb
require_dependency 'support/attendance/step_document'

module Attendance
  class StepDocument < Support::Attendance::StepDocument
    
  end
end

engines/candidate/app/models/candidate/attendance/ticket.rb
require_dependency 'support/attendance/ticket'

module Candidate
  module Attendance
    class Ticket < Support::Attendance::Ticket
      
      belongs_to :cadastre, class_name: 'Candidate::Cadastre'
      belongs_to :category, class_name: 'Candidate::Attendance::TicketCategory', foreign_key: :category_id
      
      validates :category_id, :cadastre_id, presence: true
      validate  :allow_create?

      after_create :set_situation

      private

      def set_situation
      end

      def allow_create?
        cadastre = Candidate::Cadastre.find_by(id: self.cadastre_id)
        category = Candidate::Attendance::TicketCategory.find_by(id: self.category_id)

        if !category.status
          errors.add(:base, 'Categoria não disponível.') 
          return false
        end

        if cadastre.nil?
          errors.add(:base, 'Cadastro não encontrado.')  
          return false
        end

        if !cadastre.policy.allow_new_ticket?
          errors.add(:base, 'Cadastro não tem permissão para iniciar um novo atendimento.')
          return false
        end
        
        if !category.policy.is_allow?(cadastre)
          errors.add(:base, 'Categoria não disponível.')
          return false
        end

      end
    end
  end
end

engines/candidate/app/models/candidate/attendance/ticket_category.rb
require_dependency 'support/attendance/ticket_category'

module Candidate
  module Attendance
    class TicketCategory < Support::Attendance::TicketCategory
      has_many :category_steps, class_name: 'Candidate::Attendance::TicketCategoryStep', foreign_key: :ticket_category_id 

      scope :active, -> { status_active }

      def policy
        call_policy('Candidate::Attendance::TicketPolicy', self)
      end
    end
  end
end

engines/candidate/app/models/candidate/attendance/ticket_category_step.rb
require_dependency 'support/attendance/ticket_category_step'

module Candidate
  module Attendance
    class TicketCategoryStep < Support::Attendance::TicketCategoryStep
      
    end
  end
end

engines/candidate/app/models/candidate/cadastre.rb
require_dependency 'support/candidate/cadastre'

module Candidate
  class Cadastre < Support::Candidate::Cadastre
    has_many :tickets, class_name: 'Candidate::Attendance::Ticket', foreign_key: :cadastre_id
  
    
    def policy
      call_policy('Candidate::CadastrePolicy', self)
    end
  end
end

engines/candidate/app/models/candidate/session.rb
module Candidate
  class Session
    include ActiveModel::Model

    attr_accessor :cpf, :password, :id

    validates :cpf, cpf: true, presence: true
    validates :password, presence: true
    validate  :authenticate

    private

    def authenticate
      cadastre = ::Candidate::Cadastre.find_by(cpf: self.cpf)
      cadastre_password = cadastre.password rescue nil

      if cadastre.nil? || self.password != cadastre_password 
        errors.add(:base, 'CPF ou senha incorreto.')
      else
        self.id = cadastre.id
      end
    end
  end
end

engines/candidate/app/controllers/candidate/application_controller.rb
require_dependency 'application_controller'

module Candidate
  class ApplicationController < ApplicationController
    layout 'candidate/application'

    protect_from_forgery with: :exception

    helper_method :authenticate_user!, :current_user

    private

    def authenticate_user!
      return true if !current_user.nil?
    
      redirect_to candidate.new_session_path if controller_name != 'sessions'
    end

    def current_user
      Candidate::Cadastre.find_by(id: session[:candidate_user_id])
    end


  end
end

engines/candidate/app/controllers/candidate/attendance/cadastres_controller.rb
require_dependency 'candidate/application_controller'

module Candidate
  module Attendance
    class CadastresController < ApplicationController

      def edit
      end
      
    end
  end
end

engines/candidate/app/controllers/candidate/attendance/ticket_steps_controller.rb
require_dependency 'candidate/application_controller'

module Candidate
  module Attendance
    class TicketStepsController < ApplicationController
      before_action :set_ticket

      def index
      end
      
      def show
      end
      
      private

      def set_ticket
        @ticket = Candidate::Attendance::Ticket.find(params[:ticket_id])
      end
    end
  end
end

engines/candidate/app/controllers/candidate/attendance/tickets_controller.rb
require_dependency 'candidate/application_controller'

module Candidate
  module Attendance
    class TicketsController < ApplicationController
      
      def index
        @ticket_categories = Candidate::Attendance::TicketCategory.active
      end

      def new
        @ticket_category = Candidate::Attendance::TicketCategory.find(params[:category_id])
      end

      def create
        @ticket = current_user.tickets.new
        @ticket.category_id = params[:category_id]
        
        redirect_to attendance_ticket_steps_path(1) if @ticket.save!
      end


    end
  end
end

engines/candidate/app/controllers/candidate/cadastres_controller.rb
require_dependency 'candidate/application_controller'

module Candidate
  class CadastresController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end

    def show
      @cadastre = current_user
    end

  end
end

engines/candidate/app/controllers/candidate/dashboard_controller.rb
require_dependency 'candidate/application_controller'

module Candidate
  class DashboardController < ApplicationController
    
    def index
    end

  end
end

engines/candidate/app/controllers/candidate/home_controller.rb
require_dependency 'candidate/application_controller'

module Candidate
  class HomeController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end

  end
end

engines/candidate/app/controllers/candidate/notifications_controller.rb
require_dependency 'common/application_controller'

module Candidate
  class NotificationsController < ApplicationController
    def index
    end
  end 
end

engines/candidate/app/controllers/candidate/sessions_controller.rb
require_dependency 'candidate/application_controller'

module Candidate
  class SessionsController < ApplicationController

    def new
      @session = Candidate::Session.new
    end
    
    def create
      @session = Candidate::Session.new(set_params)
      if @session.valid?
        session[:candidate_user_id] = @session.id
        redirect_to candidate.root_path
      end
    end

    private

    def set_params
      params.require(:session).permit(:cpf, :password)
    end

  end
end

engines/candidate/app/controllers/candidate/tickets_controller.rb
require_dependency 'candidate/application_controller'
module Candidate
  class TicketsController < ApplicationController
    
    def new 
    end
  end
end

engines/candidate/app/helpers/candidate/application_helper.rb
module Candidate
  module ApplicationHelper
  end
end

engines/candidate/app/views/candidate/attendance/cadastres/_form.html.haml
= simple_form_for url_for do |f|
  #first
    %p.subtitle.text-center 1. Dados básicos
    = f.input :name, input_html: { disabled: true}
    = f.input :cpf, input_html: { class: 'cpf' , disabled: true}
    = f.input :rg
    = f.input :rg_org
    = f.input :rg_uf_id, as: :select, include_blank: t(:include_blank)
    = f.input :gender_id, as: :select, include_blank: t(:include_blank)
    = f.input :born, as: :string, input_html: { class: 'date', value: nil}
    = f.input :born_uf_id, as: :select, include_blank: t(:include_blank)
    .divider
    = link_to "Prosseguir", "javascript:void(0)", class: 'button is-fullwidth is-success next', data: { show: 'second', hide: 'first'}
  #second{style: 'display: none;'}
    %p.subtitle.text-center 2. Dados complementares
    = f.input :civil_state_id, as: :select, include_blank: t(:include_blank)
    = f.input :place_birth
    = f.input :arrival_df, as: :string, input_html: { class: 'date', value: nil}
    = f.input :mother_name
    .divider
    = link_to "Prosseguir", "javascript:void(0)", class: 'button is-fullwidth is-success next', data: { show: 'third', hide: 'second'}
    .mini-divider
    = link_to "Retornar", "javascript:void(0)", class: 'button is-fullwidth is-dark next', data: { show: 'first', hide: 'second'}
  #third{style: 'display: none;'}
    %p.subtitle.text-center 3. Dados de contato
    = f.input :telephone
    = f.input :telephone_optional
    = f.input :celphone
    = f.input :email
    .divider
    = link_to "Prosseguir", "javascript:void(0)", class: 'button is-fullwidth is-success next', data: { show: 'four', hide: 'third'}
    .mini-divider
    = link_to "Retornar", "javascript:void(0)", class: 'button is-fullwidth is-dark next', data: { show: 'second', hide: 'third'}
      
  #four{style: 'display: none;'}
    %p.subtitle.text-center 4. Dados de condição especial
    = f.input :special_condition, as: :select, include_blank: false
    = f.input :special_condition_type_id, as: :select, include_blank: t(:include_blank)
    = f.input :adapted_property, as: :select, include_blank: false
    = f.input :nis
    = f.input :cid
    .divider
    = link_to "Prosseguir", "javascript:void(0)", class: 'button is-fullwidth is-success next', data: { show: 'five', hide: 'four'}
    .mini-divider
    = link_to "Retornar", "javascript:void(0)", class: 'button is-fullwidth is-dark next', data: { show: 'third', hide: 'four'}
             
  #five{style: 'display: none;'}
    %p.subtitle.text-center 5. Localização
    = f.input :state_id, as: :select, include_blank: t(:include_blank)
    = f.input :city_id, as: :select, include_blank: t(:include_blank)
    = f.input :cep
    = f.input :address
    = f.input :address_complement
    .divider
    = link_to "Prosseguir", "javascript:void(0)", class: 'button is-fullwidth is-success next', data: { show: 'six', hide: 'five'}
    .mini-divider
    = link_to "Retornar", "javascript:void(0)", class: 'button is-fullwidth is-dark next', data: { show: 'four', hide: 'five'}   
  #six{style: 'display: none;'}
    %p.subtitle.text-center 6. Informações de trabalho
    = f.input :work_cep
    = f.input :work_city_id
    = f.input :work_state_id
    = f.input :work_address
    = f.input :work_employment
    .divider
    = link_to "Prosseguir", "javascript:void(0)", class: 'button is-fullwidth is-success next', data: { show: 'seven', hide: 'six'}
    .mini-divider
    = link_to "Retornar", "javascript:void(0)", class: 'button is-fullwidth is-dark next', data: { show: 'five', hide: 'six'}        
  #seven{style: 'display: none;'}
    = f.submit 'Salvar informações', class: 'button is-fullwidth is-success'
    .mini-divider
    = link_to "Retornar", "javascript:void(0)", class: 'button is-fullwidth is-dark next ', data: { show: 'six', hide: 'seven'}        

:javascript
  $(document).ready(function() {
    $(".next").on('click', function() {
      $("#" + $(this).data('hide')).hide();
      $("#" + $(this).data('show')).fadeIn();
    });
  });

engines/candidate/app/views/candidate/attendance/cadastres/edit.html.haml
#header
  .columns
    .column.text-center
      %p.subtitle.is-5 Atendimento
#content
  .container
    .columns
      .column
        = link_to "Cancelar atualização".html_safe, attendance_ticket_steps_path(1), class: 'button is-danger is-fullwidth ', data: { disable_with: t(:disable_with)}
    .columns
      .column#app-form
        = render 'form'

engines/candidate/app/views/candidate/attendance/ticket_steps/index.html.haml
#header
  .columns
    .column.text-center
      %p.subtitle.is-5 Atendimento
#content
  .container
    .columns
      .column
        = link_to "Voltar para atendimento".html_safe, candidate.attendance_tickets_path, class: 'button is-dark is-fullwidth', data: { disable_with: t(:disable_with)}
    .columns
      .column.text-center
        %p.title.is-5 Protocolo 1
    .columns
      .column.text-center
        %p.title.is-6 Etapas
    .columns
      - @ticket.category.category_steps.order(:screen_order).each do |step|
        = link_to attendance_ticket_step_path(@ticket, step) do
          .column
            .box
              = step.name
    .columns
      .column
        = link_to "Finalizar atendimento", "#", class: 'button is-fullwidth is-success'        

engines/candidate/app/views/candidate/attendance/ticket_steps/show.html.haml
#header
  .columns
    .column.text-center
      %p.subtitle.is-5 Atendimento
#content
  .container
    .columns
      .column
        = link_to "Voltar para atendimento".html_safe, candidate.attendance_ticket_steps_path(@ticket), class: 'button is-dark is-fullwidth', data: { disable_with: t(:disable_with)}
    

engines/candidate/app/views/candidate/attendance/tickets/_new.html.haml
.modal-background.animated.fadeIn
.modal-card.animated.bounceIn
  .modal-card-head
    .modal-card-title
    %button.close-modal.delete
  .modal-card-body.text-center
    %p.subtitle.is-5 Tem certeza que deseja iniciar um novo atendimento?
    = link_to "Sim, desejo iniciar", attendance_tickets_path(category_id: @ticket_category), method: :post, class: 'close-modal button is-success is-fullwidth'
    .mini-divider
    = link_to "Cancelar", "javascript:void(0)", class: 'close-modal button is-dark is-fullwidth'

engines/candidate/app/views/candidate/attendance/tickets/index.html.haml
#header
  .columns
    .column.text-center
      %p.subtitle.is-5 Atendimento
#content
  .container
    .columns
      .column
        = link_to "Voltar para página principal".html_safe, candidate.root_path, class: 'button is-dark is-fullwidth', data: { disable_with: t(:disable_with)}
    
    - if current_user.policy.allow_new_ticket?
      .columns
        .column.text-center
          %p.title.is-6 Atendimentos disponíveis

      .columns
        - @ticket_categories.each do |category|
          - if category.policy.is_allow?(current_user)
            .column
              = link_to candidate.new_attendance_ticket_path(category_id: category.id), remote: true do
                .box
                  .columns.is-mobile
                    .column
                      %p= category.name
    - else
      .columns
        .column.text-center
          %p.title.is-6 Atendimento em progresso
      .columns
        - current_user.tickets.each do |ticket|
          .column
            = link_to candidate.attendance_ticket_steps_path(ticket) do
              .box
                = ticket.id  
    .divider

    .columns
      .column.text-center
        %p.title.is-6 Meus atendimentos
    .columns
      - if current_user.tickets.present?
        - current_user.tickets.each do |ticket|
          .column
            .box   
              .columns.is-mobile
                .column
                  %p= ticket.id            
      - else
        .column
          .box.text-center
            .columns
              .column
                = image_tag('icon-inbox.png')
              .column
                %i Você ainda não possui atendimentos realizados.

engines/candidate/app/views/candidate/attendance/tickets/new.js.haml
$(".modal").html("#{escape_javascript(render 'new')}");
$(".modal").addClass("is-active");
bulma();

engines/candidate/app/views/candidate/cadastres/index.html.haml
#candidate-header
  .columns
    .column.text-center
      %figure.image.is-64x64.is-center
        = image_tag 'no-image.png', class: 'is-rounded'
    .column.text-center
      %p.title.is-4 Elton Silva
      %p.subtitle.is-6 RII - Habilitado documentação aprovada
    .column
      .tabs.is-centered
        %ul
          %li= link_to "Ações", candidate.root_path
          %li.is-active= link_to "Meu cadastro", candidate.cadastres_path
.container
  .box
    .columns.is-mobile
      .column
        %p Lista
      .column
        %p Posição
      .column
        %p Pontuação

.container
  .box
    .columns.is-mobile
      .column
        %b Agendamentos
    .columns.is-mobile
      .column
        %p Data/Hora
      .column
        %p Situação

.container
  .box
    .columns.is-mobile
      .column
        %b Requerimentos
    .columns.is-mobile
      .column
        %p Data/Hora
      .column
        %p Situação

.container
  .box
    .columns.is-mobile
      .column
        %b Atendimentos
    .columns.is-mobile
      .column
        %p Data/Hora
      .column
        %p Situação

engines/candidate/app/views/candidate/cadastres/show.html.haml
#header
  .columns
    .column.text-center
      %p.subtitle.is-5 Meu cadastro
#content
  .container
    .columns
      .column
        = link_to "Voltar para página principal", candidate.root_path, class: 'button is-dark is-fullwidth', data: { disable_with: t(:disable_with)}

    .columns
      .column
        .box
          .columns.is-mobile
            .column
              %p
                %b Programa
              %p RII (Vulneráveis)
          .columns.is-mobile
            .column
              %p
                %b Situação cadastral
              %p asdjhakshskdj
          .columns.is-mobile
            .column
              %p
                %b Situação Processual
              %p Habiasdkasdjsd
    .columns
      .column
        .box
          .columns.is-mobile
            .column
              %b Lista
            .column
              %b Posição
            .column
              %b Pontuação
          .columns.is-mobile      
            .column
              Lista A
            .column
              1564 º
            .column
              2165456.465456
          .columns.is-mobile      
            .column
              Lista A
            .column
              1564 º
            .column
              2165456.465456
    .columns
      .column
        .box
          .columns.is-mobile
            .column
              %b Agendamentos
          .columns.is-mobile
            .column
              %p Data/Hora
            .column
              %p Situação

    .columns
      .column
        .box
          .columns.is-mobile
            .column
              %b Requerimentos
          .columns.is-mobile
            .column
              %p Data/Hora
            .column
              %p Situação

    .columns
      .column
        .box
          .columns.is-mobile
            .column
              %b Atendimentos
          .columns.is-mobile
            .column
              %p Data/Hora
            .column
              %p Situação

    .columns
      .column
        .box
          .columns.is-mobile
            .column
              %b Indicações
          .columns.is-mobile
            .column
              %p Data/Hora
            .column
              %p Situação

    .columns
      .column
        .box
          .columns.is-mobile
            .column
              %b Vínculo com entidade
          .columns.is-mobile
            .column
              %p Data/Hora
            .column
              %p Situação

engines/candidate/app/views/candidate/home/index.html.haml
#candidate-header.columns
  .column.text-center
    %figure.image.is-64x64.is-center
      = image_tag 'no-image.png', class: 'is-rounded'
  .column.text-center
    %p.title.is-4
      = current_user.presenter.short_name
    %p.subtitle.is-6
      habitliado documentação aprovada
      %br
      RII (Vulneraveis)
  .column.text-center
.container.index-content
  #candidate-links
    .big-divider
    .columns.is-gap.is-mobile.text-center
      .column
        = link_to candidate.cadastre_path(current_user) do
          = image_tag('icon-user.png')
          %p Meu cadastro
      .column
        = link_to candidate.notifications_path do
          = image_tag('icon-ring.png')
          %p Notificações
    .big-divider
    .columns.is-gap.is-mobile.text-center
      .column
        = link_to candidate.attendance_tickets_path do
          = image_tag('icon-refresh.png')
          %p Atendimento

      .column
        = link_to "#", remote: true do
          = image_tag('icon-calendar.png')
          %p Agendamento
    .big-divider
    .columns.is-mobile.text-center
      .column
        = link_to "#", remote: true do
          = image_tag('icon-enterprise.png')
          %p Indicações
      .column
        = link_to "#", remote: true do
          = image_tag('icon-contract.png')
          %p Requerimentos

engines/candidate/app/views/candidate/notifications/index.html.haml
#header
  .columns
    .column.text-center
      %p.subtitle.is-5 Notificações
#content
  .container
    .columns
      .column
        = link_to "Voltar para página principal", candidate.root_path, class: 'button is-dark is-fullwidth', data: { disable_with: t(:disable_with)}

    .columns
      .column
        - 10.times do 
          .box
            .columns
              .column
                = link_to "#" do 
                  %p
                    %b 08:00
                  %p Atualização iniciada
                  %p
                    %i Lorem ipsum la asjdn jlandahsi ausdh

engines/candidate/app/views/candidate/notifications/index.js.haml
$(".container").html("#{escape_javascript(render 'index')}");
$("#link-action").removeClass('is-active')
$("#link-notification").addClass('is-active')

engines/candidate/app/views/layouts/candidate/application.html.haml
!!!
%html
  %head
    %title WebApp
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans", rel: "stylesheet"}
    %link{href: "https://use.fontawesome.com/releases/v5.4.1/css/all.css", rel: "stylesheet"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{style: 'margin-bottom: 300px'}
    = yield
    .modal